<?php

namespace SoftEtherApi\Containers
{
    class SoftEtherError
    {
        const NoError = 'NoError';
        const ConnectFailed = 'ConnectFailed';
        const ServerIsNotVpn = 'ServerIsNotVpn';
        const Disconnected = 'Disconnected';
        const ProtocolError = 'ProtocolError';
        const ClientIsNotVpn = 'ClientIsNotVpn';
        const UserCancel = 'UserCancel';
        const AuthtypeNotSupported = 'AuthtypeNotSupported';
        const HubNotFound = 'HubNotFound';
        const AuthFailed = 'AuthFailed';
        const HubStopping = 'HubStopping';
        const SessionRemoved = 'SessionRemoved';
        const AccessDenied = 'AccessDenied';
        const SessionTimeout = 'SessionTimeout';
        const InvalidProtocol = 'InvalidProtocol';
        const TooManyConnection = 'TooManyConnection';
        const HubIsBusy = 'HubIsBusy';
        const ProxyConnectFailed = 'ProxyConnectFailed';
        const ProxyError = 'ProxyError';
        const ProxyAuthFailed = 'ProxyAuthFailed';
        const TooManyUserSession = 'TooManyUserSession';
        const LicenseError = 'LicenseError';
        const DeviceDriverError = 'DeviceDriverError';
        const InternalError = 'InternalError';
        const SecureDeviceOpenFailed = 'SecureDeviceOpenFailed';
        const SecurePinLoginFailed = 'SecurePinLoginFailed';
        const SecureNoCert = 'SecureNoCert';
        const SecureNoPrivateKey = 'SecureNoPrivateKey';
        const SecureCantWrite = 'SecureCantWrite';
        const ObjectNotFound = 'ObjectNotFound';
        const VlanAlreadyExists = 'VlanAlreadyExists';
        const VlanInstallError = 'VlanInstallError';
        const VlanInvalidName = 'VlanInvalidName';
        const NotSupported = 'NotSupported';
        const AccountAlreadyExists = 'AccountAlreadyExists';
        const AccountActive = 'AccountActive';
        const AccountNotFound = 'AccountNotFound';
        const AccountInactive = 'AccountInactive';
        const InvalidParameter = 'InvalidParameter';
        const SecureDeviceError = 'SecureDeviceError';
        const NoSecureDeviceSpecified = 'NoSecureDeviceSpecified';
        const VlanIsUsed = 'VlanIsUsed';
        const VlanForAccountNotFound = 'VlanForAccountNotFound';
        const VlanForAccountUsed = 'VlanForAccountUsed';
        const VlanForAccountDisabled = 'VlanForAccountDisabled';
        const InvalidValue = 'InvalidValue';
        const NotFarmController = 'NotFarmController';
        const TryingToConnect = 'TryingToConnect';
        const ConnectToFarmController = 'ConnectToFarmController';
        const CouldNotHostHubOnFarm = 'CouldNotHostHubOnFarm';
        const FarmMemberHubAdmin = 'FarmMemberHubAdmin';
        const NullPasswordLocalOnly = 'NullPasswordLocalOnly';
        const NotEnoughRight = 'NotEnoughRight';
        const ListenerNotFound = 'ListenerNotFound';
        const ListenerAlreadyExists = 'ListenerAlreadyExists';
        const NotFarmMember = 'NotFarmMember';
        const CipherNotSupported = 'CipherNotSupported';
        const HubAlreadyExists = 'HubAlreadyExists';
        const TooManyHubs = 'TooManyHubs';
        const LinkAlreadyExists = 'LinkAlreadyExists';
        const LinkCantCreateOnFarm = 'LinkCantCreateOnFarm';
        const LinkIsOffline = 'LinkIsOffline';
        const TooManyAccessList = 'TooManyAccessList';
        const TooManyUser = 'TooManyUser';
        const TooManyGroup = 'TooManyGroup';
        const GroupNotFound = 'GroupNotFound';
        const UserAlreadyExists = 'UserAlreadyExists';
        const GroupAlreadyExists = 'GroupAlreadyExists';
        const UserAuthtypeNotPassword = 'UserAuthtypeNotPassword';
        const OldPasswordWrong = 'OldPasswordWrong';
        const LinkCantDisconnect = 'LinkCantDisconnect';
        const AccountNotPresent = 'AccountNotPresent';
        const AlreadyOnline = 'AlreadyOnline';
        const Offline = 'Offline';
        const NotRsa1024 = 'NotRsa1024';
        const SnatCantDisconnect = 'SnatCantDisconnect';
        const SnatNeedStandalone = 'SnatNeedStandalone';
        const SnatNotRunning = 'SnatNotRunning';
        const SeVpnBlock = 'SeVpnBlock';
        const BridgeCantDisconnect = 'BridgeCantDisconnect';
        const LocalBridgeStopping = 'LocalBridgeStopping';
        const LocalBridgeUnsupported = 'LocalBridgeUnsupported';
        const CertNotTrusted = 'CertNotTrusted';
        const ProductCodeInvalid = 'ProductCodeInvalid';
        const VersionInvalid = 'VersionInvalid';
        const CaptureDeviceAddError = 'CaptureDeviceAddError';
        const VpnCodeInvalid = 'VpnCodeInvalid';
        const CaptureNotFound = 'CaptureNotFound';
        const Layer3CantDisconnect = 'Layer3CantDisconnect';
        const Layer3SwExists = 'Layer3SwExists';
        const Layer3SwNotFound = 'Layer3SwNotFound';
        const InvalidName = 'InvalidName';
        const Layer3IfAddFailed = 'Layer3IfAddFailed';
        const Layer3IfDelFailed = 'Layer3IfDelFailed';
        const Layer3IfExists = 'Layer3IfExists';
        const Layer3TableAddFailed = 'Layer3TableAddFailed';
        const Layer3TableDelFailed = 'Layer3TableDelFailed';
        const Layer3TableExists = 'Layer3TableExists';
        const BadClock = 'BadClock';
        const Layer3CantStartSwitch = 'Layer3CantStartSwitch';
        const ClientLicenseNotEnough = 'ClientLicenseNotEnough';
        const BridgeLicenseNotEnough = 'BridgeLicenseNotEnough';
        const ServerCantAccept = 'ServerCantAccept';
        const ServerCertExpires = 'ServerCertExpires';
        const MonitorModeDenied = 'MonitorModeDenied';
        const BridgeModeDenied = 'BridgeModeDenied';
        const IpAddressDenied = 'IpAddressDenied';
        const TooMantItems = 'TooMantItems';
        const MemoryNotEnough = 'MemoryNotEnough';
        const ObjectExists = 'ObjectExists';
        const Fatal = 'Fatal';
        const ServerLicenseFailed = 'ServerLicenseFailed';
        const ServerInternetFailed = 'ServerInternetFailed';
        const ClientLicenseFailed = 'ClientLicenseFailed';
        const BadCommandOrParam = 'BadCommandOrParam';
        const InvalidLicenseKey = 'InvalidLicenseKey';
        const NoVpnServerLicense = 'NoVpnServerLicense';
        const NoVpnClusterLicense = 'NoVpnClusterLicense';
        const NotAdminpackServer = 'NotAdminpackServer';
        const NotAdminpackServerNet = 'NotAdminpackServerNet';
        const BetaExpires = 'BetaExpires';
        const BrandedCToS = 'BrandedCToS';
        const BrandedCFromS = 'BrandedCFromS';
        const AutoDisconnected = 'AutoDisconnected';
        const ClientIdRequired = 'ClientIdRequired';
        const TooManyUsersCreated = 'TooManyUsersCreated';
        const SubscriptionIsOlder = 'SubscriptionIsOlder';
        const IllegalTrialVersion = 'IllegalTrialVersion';
        const NatTTwoOrMore = 'NatTTwoOrMore';
        const DuplicateDdnsKey = 'DuplicateDdnsKey';
        const DdnsHostnameExists = 'DdnsHostnameExists';
        const DdnsHostnameInvalidChar = 'DdnsHostnameInvalidChar';
        const DdnsHostnameTooLong = 'DdnsHostnameTooLong';
        const DdnsHostnameIsEmpty = 'DdnsHostnameIsEmpty';
        const DdnsHostnameTooShort = 'DdnsHostnameTooShort';
        const Mschap2PasswordNeedReset = 'Mschap2PasswordNeedReset';
        const DdnsDisconnected = 'DdnsDisconnected';
        const SpecialListenerIcmpError = 'SpecialListenerIcmpError';
        const SpecialListenerDnsError = 'SpecialListenerDnsError';
        const OpenvpnIsNotEnabled = 'OpenvpnIsNotEnabled';
        const NotSupportedAuthOnOpensource = 'NotSupportedAuthOnOpensource';
        const Vpngate = 'Vpngate';
        const VpngateClient = 'VpngateClient';
        const VpngateInclientCantStop = 'VpngateInclientCantStop';
        const NotSupportedFunctionOnOpensource = 'NotSupportedFunctionOnOpensource';

        const ErrorList = [
            0 => 'NoError',
            1 => 'ConnectFailed',
            2 => 'ServerIsNotVpn',
            3 => 'Disconnected',
            4 => 'ProtocolError',
            5 => 'ClientIsNotVpn',
            6 => 'UserCancel',
            7 => 'AuthtypeNotSupported',
            8 => 'HubNotFound',
            9 => 'AuthFailed',
            10 => 'HubStopping',
            11 => 'SessionRemoved',
            12 => 'AccessDenied',
            13 => 'SessionTimeout',
            14 => 'InvalidProtocol',
            15 => 'TooManyConnection',
            16 => 'HubIsBusy',
            17 => 'ProxyConnectFailed',
            18 => 'ProxyError',
            19 => 'ProxyAuthFailed',
            20 => 'TooManyUserSession',
            21 => 'LicenseError',
            22 => 'DeviceDriverError',
            23 => 'InternalError',
            24 => 'SecureDeviceOpenFailed',
            25 => 'SecurePinLoginFailed',
            26 => 'SecureNoCert',
            27 => 'SecureNoPrivateKey',
            28 => 'SecureCantWrite',
            29 => 'ObjectNotFound',
            30 => 'VlanAlreadyExists',
            31 => 'VlanInstallError',
            32 => 'VlanInvalidName',
            33 => 'NotSupported',
            34 => 'AccountAlreadyExists',
            35 => 'AccountActive',
            36 => 'AccountNotFound',
            37 => 'AccountInactive',
            38 => 'InvalidParameter',
            39 => 'SecureDeviceError',
            40 => 'NoSecureDeviceSpecified',
            41 => 'VlanIsUsed',
            42 => 'VlanForAccountNotFound',
            43 => 'VlanForAccountUsed',
            44 => 'VlanForAccountDisabled',
            45 => 'InvalidValue',
            46 => 'NotFarmController',
            47 => 'TryingToConnect',
            48 => 'ConnectToFarmController',
            49 => 'CouldNotHostHubOnFarm',
            50 => 'FarmMemberHubAdmin',
            51 => 'NullPasswordLocalOnly',
            52 => 'NotEnoughRight',
            53 => 'ListenerNotFound',
            54 => 'ListenerAlreadyExists',
            55 => 'NotFarmMember',
            56 => 'CipherNotSupported',
            57 => 'HubAlreadyExists',
            58 => 'TooManyHubs',
            59 => 'LinkAlreadyExists',
            60 => 'LinkCantCreateOnFarm',
            61 => 'LinkIsOffline',
            62 => 'TooManyAccessList',
            63 => 'TooManyUser',
            64 => 'TooManyGroup',
            65 => 'GroupNotFound',
            66 => 'UserAlreadyExists',
            67 => 'GroupAlreadyExists',
            68 => 'UserAuthtypeNotPassword',
            69 => 'OldPasswordWrong',
            73 => 'LinkCantDisconnect',
            74 => 'AccountNotPresent',
            75 => 'AlreadyOnline',
            76 => 'Offline',
            77 => 'NotRsa1024',
            78 => 'SnatCantDisconnect',
            79 => 'SnatNeedStandalone',
            80 => 'SnatNotRunning',
            81 => 'SeVpnBlock',
            82 => 'BridgeCantDisconnect',
            83 => 'LocalBridgeStopping',
            84 => 'LocalBridgeUnsupported',
            85 => 'CertNotTrusted',
            86 => 'ProductCodeInvalid',
            87 => 'VersionInvalid',
            88 => 'CaptureDeviceAddError',
            89 => 'VpnCodeInvalid',
            90 => 'CaptureNotFound',
            91 => 'Layer3CantDisconnect',
            92 => 'Layer3SwExists',
            93 => 'Layer3SwNotFound',
            94 => 'InvalidName',
            95 => 'Layer3IfAddFailed',
            96 => 'Layer3IfDelFailed',
            97 => 'Layer3IfExists',
            98 => 'Layer3TableAddFailed',
            99 => 'Layer3TableDelFailed',
            100 => 'Layer3TableExists',
            101 => 'BadClock',
            102 => 'Layer3CantStartSwitch',
            103 => 'ClientLicenseNotEnough',
            104 => 'BridgeLicenseNotEnough',
            105 => 'ServerCantAccept',
            106 => 'ServerCertExpires',
            107 => 'MonitorModeDenied',
            108 => 'BridgeModeDenied',
            109 => 'IpAddressDenied',
            110 => 'TooMantItems',
            111 => 'MemoryNotEnough',
            112 => 'ObjectExists',
            113 => 'Fatal',
            114 => 'ServerLicenseFailed',
            115 => 'ServerInternetFailed',
            116 => 'ClientLicenseFailed',
            117 => 'BadCommandOrParam',
            118 => 'InvalidLicenseKey',
            119 => 'NoVpnServerLicense',
            120 => 'NoVpnClusterLicense',
            121 => 'NotAdminpackServer',
            122 => 'NotAdminpackServerNet',
            123 => 'BetaExpires',
            124 => 'BrandedCToS',
            125 => 'BrandedCFromS',
            126 => 'AutoDisconnected',
            127 => 'ClientIdRequired',
            128 => 'TooManyUsersCreated',
            129 => 'SubscriptionIsOlder',
            130 => 'IllegalTrialVersion',
            131 => 'NatTTwoOrMore',
            132 => 'DuplicateDdnsKey',
            133 => 'DdnsHostnameExists',
            134 => 'DdnsHostnameInvalidChar',
            135 => 'DdnsHostnameTooLong',
            136 => 'DdnsHostnameIsEmpty',
            137 => 'DdnsHostnameTooShort',
            138 => 'Mschap2PasswordNeedReset',
            139 => 'DdnsDisconnected',
            140 => 'SpecialListenerIcmpError',
            141 => 'SpecialListenerDnsError',
            142 => 'OpenvpnIsNotEnabled',
            143 => 'NotSupportedAuthOnOpensource',
            144 => 'Vpngate',
            145 => 'VpngateClient',
            146 => 'VpngateInclientCantStop',
            147 => 'NotSupportedFunctionOnOpensource',
        ];
    }
}